server:
  port: 8081

spring:
  profiles:
    # 默认激活dev
    active: dev
  application:
    name: yeah-app

# for actuator, health endpoint
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

# 接口文档相关
springdoc:
  swagger-ui:
    path: /doc.html

# dataSource decorator by p6spy
# https://baomidou.com/guides/p6spy/
# https://github.com/gavlyukovskiy/spring-boot-data-source-decorator
decorator:
  datasource:
    p6spy:
      # Register P6LogFactory to log JDBC events
      enable-logging: true
      # Custom log format, if specified com.p6spy.engine.spy.appender.CustomLineFormat will be used with this log format
      # see https://p6spy.readthedocs.io/en/latest/configandusage.html#customlogmessageformat
      log-format: "id: %(connectionId) | t: %(currentTime) | d: %(executionTime)ms | c: %(category) | sql: \n\t%(sqlSingleLine)"
      # Exclude certain categories from logging. If specified only matched messages will be logged.
      # see https://p6spy.readthedocs.io/en/latest/configandusage.html#excludecategories
      exclude-categories: "info,debug,result,resultset,commit,rollback"

yeah-boot:
  # app模块单独启动/打包的时候启用@MapperScan
  app-mapper-scan-enabled: true
  # ID编号生成器
  id-generator:
    alphabet: GQT0FNR3taz1vDVEjsSJ2biZmLB8qk6OCMndohlKf4IAw7xr9eYgXWPcuHpU5y
    min-length: 8
  # 消息队列 配置见MqProperties类
  mq:
    # 实现：redis | rabbitmq
#    impl: redis
    auto-ack: true
