server:
  port: 8082

spring:
  application:
    name: yeah-merchant
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    url: jdbc:mysql://${spring.datasource.host}:3306/yeah_mall?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useUnicode=true&zeroDateTimeBehavior=CONVERT_TO_NULL&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&allowMultiQueries=false&nullCatalogMeansCurrent=true&rewriteBatchedStatements=true&useAffectedRows=false
    username: root
    password: 123456
  # redis
  redis:
    host: localhost
    port: 6379
    password: ""
    database: 1
    timeout: 10000

# dataSource decorator by p6spy
# https://baomidou.com/guides/p6spy/
# https://github.com/gavlyukovskiy/spring-boot-data-source-decorator
decorator:
  datasource:
    p6spy:
      # Register P6LogFactory to log JDBC events
      enable-logging: true
      # Custom log format, if specified com.p6spy.engine.spy.appender.CustomLineFormat will be used with this log format
      # see https://p6spy.readthedocs.io/en/latest/configandusage.html#customlogmessageformat
      log-format: "id: %(connectionId) | t: %(currentTime) | d: %(executionTime)ms | c: %(category) | sql: \n\t%(sqlSingleLine)"
      # Exclude certain categories from logging. If specified only matched messages will be logged.
      # see https://p6spy.readthedocs.io/en/latest/configandusage.html#excludecategories
      exclude-categories: "info,debug,result,resultset,commit,rollback"

# auth相关
auth:
  token:
    # 全局jwt配置（subject中可覆盖）
    jwt:
      # 签发密钥
      secret: uzae2ohch7shiLod6eghepheiHiebai5
      # 过期时间（秒）
      expire-seconds: 3600
      # 时间校验偏差（秒）
      default-leeway: 60
    subjects:
      - name: mch
        jwt:
          # 签发密钥
          secret: oojah0Il4eu4Wietohcooquee5fooque
          # 过期时间（秒）
          expire-seconds: 3600
          # 时间校验偏差（秒）
          default-leeway: 60
        terminals:
          - name: web
            # 同一个账号在该终端的最大在线token数量（默认-1，表示不限制）（不可超过总的最大在线token数量）
            max-online-token-count: -1
          - name: api
            # 同一个账号在该终端的最大在线token数量（默认-1，表示不限制）（不可超过总的最大在线token数量）
            max-online-token-count: -1
        # 同一个账号的最大在线token数量（默认-1，表示不限制）
        max-online-token-count: 10
        # 同一个账号的最大在线终端数量（默认-1，表示不限制）
        max-online-terminal-count: -1

# ManticoreSearch
manticore-search:
  base-path: http://localhost:9308

yeah-boot:
  # 是否开启验证码校验
  captcha-enabled: false
  # ID编号生成器
  id-generator:
    alphabet: GQT0FNR3taz1vDVEjsSJ2biZmLB8qk6OCMndohlKf4IAw7xr9eYgXWPcuHpU5y
    min-length: 8