server:
  port: 8080

spring:
  profiles:
    # 默认激活dev
    active: dev
  application:
    name: yeah-admin
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# for actuator, health endpoint
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

# 接口文档相关
springdoc:
  swagger-ui:
    path: /doc.html

# dataSource decorator by p6spy
# https://baomidou.com/guides/p6spy/
# https://github.com/gavlyukovskiy/spring-boot-data-source-decorator
decorator:
  datasource:
    p6spy:
      # Register P6LogFactory to log JDBC events
      enable-logging: true
      # Custom log format, if specified com.p6spy.engine.spy.appender.CustomLineFormat will be used with this log format
      # see https://p6spy.readthedocs.io/en/latest/configandusage.html#customlogmessageformat
      log-format: "id: %(connectionId) | t: %(currentTime) | d: %(executionTime)ms | c: %(category) | sql: \n\t%(sqlSingleLine)"
      # Exclude certain categories from logging. If specified only matched messages will be logged.
      # see https://p6spy.readthedocs.io/en/latest/configandusage.html#excludecategories
      exclude-categories: "info,debug,result,resultset,commit,rollback"

# mybatis-plus相关
mybatis-plus:
  global-config:
    db-config:
      # 实体查询时，字段为非空串才设置查询条件
      select-strategy: not_empty

yeah-boot:
  # 是否为安全模式（场景：跳过@PreAuthorize @pms.hasPermission权限校验，方便权限配置或其他场景；一般为false，不需要动）
  safe-mode: false
  # 超级管理员账号，该账号可以跳过权限校验
  super-admin: ''
  # ID编号生成器
  id-generator:
    alphabet: GQT0FNR3taz1vDVEjsSJ2biZmLB8qk6OCMndohlKf4IAw7xr9eYgXWPcuHpU5y
    min-length: 8
  # 代码生成器
  code-generator:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    author: yeshimin
    pack: com.yeshimin.yeahboot
    module: admin
    table-prefix:
      - t_
      - s_
    base-entity-fields:
      - id
      - deleteTime
      - deleted
      - createTime
      - createBy
      - updateTime
      - updateBy
  # Websocket相关
  websocket:
    heartbeat:
      # 是否启用心跳检测
      enabled: false
      # 心跳检测间隔（秒）
      interval: 30
      # 心跳检测超时时间（秒）
      timeout: 90